services:
  web:
    build:
      context: .
      dockerfile: TravelBook/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/docker-data/certs:/https:ro
      - ./secrets:/run/secrets:ro   # dossier local contenant les secrets
    environment:
      ASPNETCORE_URLS: "https://+443;http://+80"
      ASPNETCORE_HTTPS_PORT: 443
      AZURE_CLIENT_ID_FILE: /run/secrets/travelbook_azure_client_id
      AZURE_CLIENT_SECRET_FILE: /run/secrets/travelbook_azure_client_secret
      AZURE_TENANT_ID_FILE: /run/secrets/travelbook_azure_tenant_id
      KEYVAULT_URI_FILE: /run/secrets/travelbook_keyvault_uri
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/travelbook.pfx
      ASPNETCORE_Kestrel__Certificates__Default__PasswordFile: /run/secrets/travelbook_pfx_password

