services:
  web:
    image: travelbook_app:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/docker-data/certs:/https:ro
    secrets:
      - travelbook_pfx_password
    environment:
      ASPNETCORE_URLS="https://+443;http://+80"
      ASPNETCORE_HTTPS_PORT=443
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/travelbook.pfx
      ASPNETCORE_Kestrel__Certificates__Default__PasswordFile: /run/secrets/travelbook_pfx_password
    deploy:
      replicas: 1
      restart_policy:
        condition: none

secrets:
  travelbook_pfx_password:
    external: true
