version: "3.9"

services:
  travelbook:
    build:
      context: ./TravelBook
      dockerfile: Dockerfile
    container_name: travelbook
    ports:
      - "8080:8080"
    volumes:
      - /data/docker-data/certs:/https:ro
    secrets:
      - travelbook_pfx_password
    environment:
      ASPNETCORE_URLS: https://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/travelbook.pfx
      ASPNETCORE_Kestrel__Certificates__Default__PasswordFile: /run/secrets/travelbook_pfx_password
    restart: unless-stopped

secrets:
  travelbook_pfx_password:
    external: true
